### ISSUE TITLE
The Square not on venues page

### ISSUE THREAD

**Issue by joestrong** [waveney/wmff#508]
Noticed The Square doesn't seem to appear on the Venues page: https://wimbornefolk.co.uk/WhatsOnWhere.php

I would guess there should be a link to: https://wimbornefolk.co.uk/int/VenueShow.php?v=64

**Comment by waveney** [comment]
Thanks,

Something broke, done a quick hack fix properly later.

Richard

**Comment by waveney** [comment]
Now fixed (a missing bracket in some SQL) .   Thanks for reporting it.
